"""add language to posts

Revision ID: 914308fe9944
Revises: 93f06a873fe0
Create Date: 2020-04-15 12:33:15.225407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914308fe9944'
down_revision = '93f06a873fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
